package:
  name: zlib
  version: "1.2.8"

source:
  fn:  zlib-1.2.8.tar.gz
  url:  http://zlib.net/zlib-1.2.8.tar.gz
  sha1: a4d316c404ff54ca545ea71a27af7dbc29817088

build:
  number: 0

requirements:
  build:
    - gcc

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libz.so.1.2.8) # [linux]
    - exit $(test -f ${PREFIX}/lib/libz.1.2.8.dylib) # [osx]
